/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.copper.manufacturing;

import biz.iteksolutions.IPrinterOutput;
import static com.copper.manufacturing.PrintTestMain.setupPort;
import com.fazecast.jSerialComm.SerialPort;
import java.util.ArrayList;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author alan
 */
public class TesterPanel extends javax.swing.JPanel 
         implements IPrinterOutput 
{

    private SerialPort port;
    private SerialPort[] port_list;
    private PrinterThread printer_thread;
    
    /**
     * Creates new form TesterPanel
     */
    public TesterPanel() {
        initComponents();
        
        button_openclose.setText("Open");
        port = null;
    }
    
    private ComboBoxModel getGuiPorts()
    {
        var items = new ArrayList<String>();
        
        port_list = SerialPort.getCommPorts();
        for (var p : port_list) {
            items.add(p.getSystemPortName());
        }
        String[] tp = items.toArray(new String[items.size()]);
        return new DefaultComboBoxModel<>(tp);
    }
    
    
    /*** IPrinterOutput methods ***/
    
    /**
     * append text to main display
     * @param text 
     */
    @Override
    public void setText(String text) {
        if (text == null || text.isEmpty()) {
            return;
        }
        txtDisplay.append(text);
    }

    @Override
    public void clearPrinter() {
        txtDisplay.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();
        p_baud_rate = new javax.swing.JComboBox<>();
        p_ports = new javax.swing.JComboBox<>();
        button_openclose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        button_clear = new javax.swing.JButton();

        setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N

        txtDisplay.setColumns(20);
        txtDisplay.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        txtDisplay.setRows(5);
        jScrollPane1.setViewportView(txtDisplay);

        p_baud_rate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9600", "19200", "38400" }));

        p_ports.setModel(getGuiPorts());

        button_openclose.setText("open_close");
        button_openclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_opencloseActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Port");

        button_clear.setText("Clear");
        button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_ports, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_baud_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_openclose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_baud_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_ports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_openclose)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_clear)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_opencloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_opencloseActionPerformed
        if (port == null) {
            var iport = p_ports.getSelectedIndex();
            var p = port_list[iport];
            
            setupPort(p);
            var s_baud = (String)p_baud_rate.getSelectedItem();
            var baud = Integer.parseInt(s_baud);          
            p.setBaudRate(baud);          

            p.openPort();
            if (!p.isOpen()) {
                setText("== Couldn't open port " + p.getSystemPortName() + "\n");
            }           

            var pt = new PrinterThread(this, 
                p.getInputStream(), p.getOutputStream()); 
            pt.start();
           
            setText("== Port " + p.getSystemPortName() + " opened at " +
                    s_baud + "\n");         
            port = p;
            printer_thread = pt;
            p_baud_rate.setEnabled(false);
            p_ports.setEnabled(false);
            button_openclose.setText("Close");
            
        } else {
            port.closePort();
            PrinterThread.endit(printer_thread);
            
            port = null;
            printer_thread = null;

            p_baud_rate.setEnabled(true);
            p_ports.setEnabled(true);            
            button_openclose.setText("Open");            
        }
    }//GEN-LAST:event_button_opencloseActionPerformed

    private void button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearActionPerformed
        txtDisplay.setText("");
    }//GEN-LAST:event_button_clearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_clear;
    private javax.swing.JButton button_openclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> p_baud_rate;
    private javax.swing.JComboBox<String> p_ports;
    private javax.swing.JTextArea txtDisplay;
    // End of variables declaration//GEN-END:variables
}
